[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

#[lib]
#crate-type = ["cdylib", "rlib"]

[dependencies]
models = { version = "0.1.0", path = "../models" }
yew = { version = "0.20.0", features = ["csr"] }
