
[serve]
# The address to serve on.
#address = "127.0.0.1"
# The port to serve on.
port = 9000
# Open a browser tab once the initial build is complete.
open = true
# Disable auto-reload of the web app.
#no_autoreload = false


#[[proxy]]
#rewrite = "/api/v1/"
#backend = "http://localhost:9000/"
